server {
    listen 80;
    server_name IP_ТВОЕГО_СЕРВЕРА;

    root /var/www/AutoRent/frontend/dist;
    index index.html;

    client_max_body_size 20M;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://unix:/var/www/AutoRent/autorent.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://unix:/var/www/AutoRent/autorent.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /var/www/AutoRent/staticfiles/;
    }

    location /media/ {
        alias /var/www/AutoRent/media/;
    }
}
