# Generated by Django 6.0 on 2025-12-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('low', 'Низкий сегмент'), ('middle', 'Средний сегмент'), ('luxury', 'Люкс')], default='middle', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат')], default='manual', max_length=20),
        ),
    ]
