# Generated by Django 6.0 on 2025-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20),
        ),
    ]
